### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by dominiklessel**
- New password now shown in email
- Activation field now written to the right place in the data array
- Add base route for "forgotten_password" inside the readme

### CODE REVIEW

**Comment by voidet** [comment]
Thanks for the pull request.
May I ask why adding $this->data[$model][$useractive_field] = true; instead of using request fixed a bug?
I was under the impression this->data can no longer be modified instead you should use the request object.

**Comment by dominiklessel** [comment]
I'm using the latest version of CakePHP and Cake can't access data through the request object. Also Cake raises an "Indirect modification of overloaded property SignMeUpComponent::$request has no effect"-exception

**Comment by voidet** [comment]
Sorry I don't believe that is true with 2.1 with the request object as with cake 2.1 $this->data is to be "read only" and properties should now be accessed via $this->request->data. So would you be able to post the errors you have been getting and I will try look closer as to why.

**Comment by dominiklessel** [comment]
My version.txt says I'm using 2.1.2 and I'm not abled to acces the request object in your component using this pattern (which I usually use inside my controllers):

```
if ($this->request->is('post')) {
  print_r($this->request->data);
}

>> Fatal error: Call to a member function is() on a non-object in /var/www/default/http_docs/app/Plugin/sign_me_up/Controller/Component/SignMeUpComponent.php on line 82
```

Seems like the object is not even available …

I'll investigate why it's not working as it should

**Comment by voidet** [comment]
This issue has been resolved for 2.1.2.
Many thanks for your contributions.

**Pull request closed without merging**
