### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by voidet** [comment]
Interesting I will test this out thank you

**Comment by voidet** [comment]
Can you please paste your routes?

**Comment by ghost** [comment]
Just the default ones:

``` php
Router::connect('/', array('controller' => 'pages', 'action' => 'display', 'home'));
Router::connect('/pages/*', array('controller' => 'pages', 'action' => 'display'));
```

**Comment by voidet** [comment]
Okay,
Please use the correct routes as this is to obfuscate DB field names from the URL:

Router::connect('/activate/:activation_code', array('controller' => 'users', 'action' => 'activate'), array('pass' => 'activation_code'));

This should then resolve this issue.

**Comment by ghost** [comment]
Thanks, I had overlooked that.

**Pull request closed without merging**
